# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Desing.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(500, 500)
        MainWindow.setMinimumSize(QtCore.QSize(500, 500))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.Today = QtWidgets.QPushButton(self.centralwidget)
        self.Today.setMaximumSize(QtCore.QSize(60, 100))
        self.Today.setObjectName("Today")
        self.gridLayout.addWidget(self.Today, 2, 0, 1, 1)
        self.Timer = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Lucida Sans")
        font.setPointSize(25)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.Timer.setFont(font)
        self.Timer.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.Timer.setTextFormat(QtCore.Qt.AutoText)
        self.Timer.setAlignment(QtCore.Qt.AlignCenter)
        self.Timer.setObjectName("Timer")
        self.gridLayout.addWidget(self.Timer, 0, 0, 1, 5)
        self.textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit.setMaximumSize(QtCore.QSize(150, 40))
        font = QtGui.QFont()
        font.setFamily("MS UI Gothic")
        self.textEdit.setFont(font)
        self.textEdit.setObjectName("textEdit")
        self.gridLayout.addWidget(self.textEdit, 1, 2, 1, 1)
        self.StartButton = QtWidgets.QPushButton(self.centralwidget)
        self.StartButton.setMinimumSize(QtCore.QSize(150, 40))
        self.StartButton.setMaximumSize(QtCore.QSize(300, 40))
        self.StartButton.setWhatsThis("")
        self.StartButton.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.StartButton.setAutoFillBackground(False)
        self.StartButton.setIconSize(QtCore.QSize(16, 16))
        self.StartButton.setCheckable(False)
        self.StartButton.setAutoDefault(False)
        self.StartButton.setDefault(False)
        self.StartButton.setFlat(False)
        self.StartButton.setObjectName("StartButton")
        self.gridLayout.addWidget(self.StartButton, 2, 2, 1, 1)
        self.Calendar = QtWidgets.QPushButton(self.centralwidget)
        self.Calendar.setMaximumSize(QtCore.QSize(60, 100))
        self.Calendar.setObjectName("Calendar")
        self.gridLayout.addWidget(self.Calendar, 2, 4, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "ComicTracker"))
        self.Today.setText(_translate("MainWindow", "Today"))
        self.Timer.setText(_translate("MainWindow", "00:00:00"))
        self.textEdit.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS UI Gothic\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\';\">What are you doing?</span></p></body></html>"))
        self.StartButton.setText(_translate("MainWindow", "Start"))
        self.Calendar.setText(_translate("MainWindow", "Calendar"))
