# @Author: Daniil Maslov
# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'todayWindowDesign.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_todayWindow(object):
    def setupUi(self, todayWindow):
        todayWindow.setObjectName("todayWindow")
        todayWindow.setEnabled(True)
        todayWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(todayWindow)
        self.centralwidget.setObjectName("centralwidget")
        todayWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(todayWindow)
        self.statusbar.setObjectName("statusbar")
        todayWindow.setStatusBar(self.statusbar)

        self.retranslateUi(todayWindow)
        QtCore.QMetaObject.connectSlotsByName(todayWindow)

    def retranslateUi(self, todayWindow):
        _translate = QtCore.QCoreApplication.translate
        todayWindow.setWindowTitle(_translate("todayWindow", "ComicTracker"))
