# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'todayWindowDesign.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_todayWindow(object):
    def setupUi(self, todayWindow):
        todayWindow.setObjectName("todayWindow")
        todayWindow.setEnabled(True)
        todayWindow.resize(812, 600)
        self.centralwidget = QtWidgets.QWidget(todayWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 10, 791, 581))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.graphicsView = QtWidgets.QGraphicsView(self.gridLayoutWidget)
        self.graphicsView.setObjectName("graphicsView")
        self.gridLayout.addWidget(self.graphicsView, 0, 0, 1, 1)
        todayWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(todayWindow)
        QtCore.QMetaObject.connectSlotsByName(todayWindow)

    def retranslateUi(self, todayWindow):
        _translate = QtCore.QCoreApplication.translate
        todayWindow.setWindowTitle(_translate("todayWindow", "ComicTracker"))
