# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'design.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(500, 500)
        MainWindow.setMinimumSize(QtCore.QSize(500, 500))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.calendarButton = QtWidgets.QPushButton(self.centralwidget)
        self.calendarButton.setMaximumSize(QtCore.QSize(60, 100))
        self.calendarButton.setObjectName("calendarButton")
        self.gridLayout.addWidget(self.calendarButton, 2, 0, 1, 1)
        self.clock = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Lucida Sans")
        font.setPointSize(25)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.clock.setFont(font)
        self.clock.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.clock.setTextFormat(QtCore.Qt.AutoText)
        self.clock.setAlignment(QtCore.Qt.AlignCenter)
        self.clock.setObjectName("clock")
        self.gridLayout.addWidget(self.clock, 0, 0, 1, 5)
        self.whatWillYouDo = QtWidgets.QTextEdit(self.centralwidget)
        self.whatWillYouDo.setMaximumSize(QtCore.QSize(150, 40))
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        self.whatWillYouDo.setFont(font)
        self.whatWillYouDo.setObjectName("whatWillYouDo")
        self.gridLayout.addWidget(self.whatWillYouDo, 1, 2, 1, 1)
        self.startButton = QtWidgets.QPushButton(self.centralwidget)
        self.startButton.setMinimumSize(QtCore.QSize(150, 40))
        self.startButton.setMaximumSize(QtCore.QSize(300, 40))
        self.startButton.setWhatsThis("")
        self.startButton.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.startButton.setAutoFillBackground(False)
        self.startButton.setIconSize(QtCore.QSize(16, 16))
        self.startButton.setCheckable(False)
        self.startButton.setAutoDefault(False)
        self.startButton.setDefault(False)
        self.startButton.setFlat(False)
        self.startButton.setObjectName("startButton")
        self.gridLayout.addWidget(self.startButton, 2, 2, 1, 1)
        self.todayButton = QtWidgets.QPushButton(self.centralwidget)
        self.todayButton.setMaximumSize(QtCore.QSize(60, 100))
        self.todayButton.setObjectName("todayButton")
        self.gridLayout.addWidget(self.todayButton, 2, 4, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "ComicTracker"))
        self.calendarButton.setText(_translate("MainWindow", "Calendar"))
        self.clock.setText(_translate("MainWindow", "00:00:00"))
        self.whatWillYouDo.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Reference Sans Serif\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'MS UI Gothic\';\"><br /></p></body></html>"))
        self.whatWillYouDo.setPlaceholderText(_translate("MainWindow", "What will you do?"))
        self.startButton.setText(_translate("MainWindow", "Start"))
        self.todayButton.setText(_translate("MainWindow", "Today"))
